


server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # 🔥 PROXY API REQUESTS
    location /predict {
        proxy_pass http://api:8000/predict;
    }

    location /health {
        proxy_pass http://api:8000/health;
    }

    location /ready {
        proxy_pass http://api:8000/ready;
    }

    location /drift/ {
        proxy_pass http://api:8000/drift/;
    }

    # Serve pipeline page
    location = /pipeline {
        try_files /pipeline.html =404;
    }

    # SPA fallback
    location / {
        try_files $uri $uri/ /index.html;
    }
}